### ISSUE TITLE
Requirements for Final Presentation on Monday

### ISSUE THREAD

**Issue by lassesteffen** [janwestphal306/edtrio#11]
- [x] Antworten je nach prozentualem Anteil der Votes einfärben
- [x]  Pro Antwort die Votes für diesen zeigen
- [x] In der Poll anzeigen 17/20 haben abgestimmt
- [x] Delete von Poll
- [x] Delete von Answer
- [x] Bessere Lösung für Placeholder
- [x] Style den Text 'Du hast schon abgestimmt'
- [x] add different users to simulate voting
- [x] style total vote count

**Comment by konstantinjdobler** [comment]
Wenn deleten von poll incl answers funktioniert, müssen der alte poll noch gelöscht werden wenn ein neues template ausgewählt wird
